### ISSUE TITLE
Support OpenUPM

### ISSUE THREAD

**Issue by rhys-vdw** [ogxd/project-curator#14]
Hi, could you please tag your releases for OpenUPM support? It seems somebody has already added this repo to OpenUPM but it has not been pulled in due to tags being malformed. For compatibility they will need to use the full semver string (i.e. `1.4.0` instead of `1.4`).

https://openupm.com/packages/com.ogxd.project-curator/

I'd open a PR but I don't think I can include tags in a PR?

**Comment by ogxd** [comment]
Done! I just pushed a 1.4.0 tag (and created a release, not sure if necessary or not).   
Thanks for creating that issue @rhys-vdw :)

**Comment by rhys-vdw** [comment]
Yeah that works. You can see the page is live now. Cheers.

This project rules btw. It's superior to the paid "Asset Cleaner Pro".
