### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by JudgeGroovyman** [ogxd/project-curator#2]
Thanks for sharing your open source project.  It looks like you haven't specified a license.

### Some Background ###
When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

[choosealicense.com](choosealicense.com) is a great resource to learn about open source software licensing and the MIT License seems to be what most Unity related projects on here are using.

Thanks again,
John

**Comment by ogxd** [comment]
Added WTFPL license :)
