### ISSUE TITLE
Editor freezes when deleting a lot of "not included" assets

### ISSUE THREAD

**Issue by R-Faber** [ogxd/project-curator#8]
The project freezes the editor when deleting a lot of "not included" assets.
It might have something to do with rebuilding the database upon removal of an asset, for each asset individually?

Versions:
Unity 2019.3.32f1
Project Curator 1.2.0

**Comment by ogxd** [comment]
Hello @R-Faber , thanks for the feedback!   
Indeed, currently, the database is re-serialized (not rebuilt, though, the tool is able to update the database without having to rebuild it every time).    
There is a way to do the re-serialization after a batch of operation ;)

**Comment by ogxd** [comment]
Here is the latest version with this improvement [Project Curator 1.4](https://github.com/ogxd/project-curator/releases/tag/1.4)    
Have fun creating!
